name: Python Function App with Service Bus
 
on:
  push:
    branches:
      - dev
      - stage
      - master
 
jobs:
  build-and-deploy:
    strategy:
      matrix:
        environment: ['dev', 'stage', 'prod']
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
 
    - name: Setup Python Environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
 
    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
 
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ secrets[format('AZURE_FUNCTIONAPP_NAME_{0}', matrix.environment.toUpperCase())] }}
        package: '.'
        publish-profile: ${{ secrets[format('AZURE_FUNCTIONAPP_PUBLISH_PROFILE_{0}', matrix.environment.toUpperCase())] }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true